name: customer_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version:  1.1.0+18  # update next version number  1.1.1+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: any
  json_annotation: any
  freezed_annotation: any
  get: ^4.3.8
  sizer: ^2.0.13
  badges: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2
  flutter_svg: ^1.0.1
  font_awesome_flutter: ^9.1.0
  toggle_switch: ^1.4.0

  flutter_statusbarcolor_ns: ^0.4.0
  timelines: ^0.1.0
  animated_text_kit: ^4.2.1
  graphql_flutter: ^5.1.0
  google_maps_flutter: ^2.2.0
  geolocator: ^8.0.0
  geocode: ^1.0.1
  flutter_spinkit: ^5.1.0
  loading_overlay: ^0.3.0
  get_storage: ^2.0.3
  lottie: ^1.2.1
  flutter_share_me: ^1.0.0
  firebase_dynamic_links:  ^4.1.1
  get_it:
  flutter_switch: ^0.3.2
  path_provider:
  permission_handler: ^8.3.0
 
  location: ^4.3.0
  geocoding: ^2.0.1
  buttons_tabbar: 1.3.2
  cached_network_image: ^3.2.0
  email_validator: ^2.1.17
  flutter_feather_icons: ^2.0.0+1
  firebase_crashlytics: ^2.8.11
  firebase_performance: ^0.8.0+2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.3
  rename: ^2.0.1
  shimmer: ^2.0.0
  flutter_toggle_tab: ^1.1.7
  pinput: ^1.2.2
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.2.0
  # internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^2.3.9
  google_place: ^0.4.7
  intl:
  stream_chat_flutter: ^3.4.0
  awesome_dialog: ^2.2.1
  firebase_remote_config:
  camera: ^0.9.4+22
  razorpay_flutter: ^1.3.0
  uni_links: ^0.5.1
  dio: ^4.0.4
  freshchat_sdk: ^0.9.7
  image_picker: ^0.8.6
  photo_view: ^0.13.0
  dotted_border: ^2.0.0+3
  webview_flutter: ^3.0.4
  upgrader: ^4.9.0

  #debugging
  logger: ^1.1.0
  bubble: ^1.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  keyboard_actions: ^3.3.1
  # firebase_app_check: ^0.0.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  freezed: any
  platform: ^3.1.0
  

  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  flutter_launcher_icons: "^0.9.2"

dependency_overrides:
  video_compress: ^3.1.1
  wakelock: ^0.5.1+1
  firebase_core_platform_interface: 4.5.1
  web_socket_channel: 2.2.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/customerlogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/mockups/
    - assets/icons/
    - assets/lottie/
    - assets/map/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MuseoSans
      fonts:
        - asset: assets/fonts/MuseoSans-300.otf
          weight: 300

        - asset: assets/fonts/MuseoSans_500.otf
          weight: 500

        - asset: assets/fonts/MuseoSans_700.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
